In [28]:
import os
import pandas as pd
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt

In [29]:
main = pd.read_csv('input_data/3_ML_outputs/datasets/PredictingSLResistanceFeatures_main.csv')
main

/var/folders/cs/dzdz0ppx7lld40ztphtqg_dh0000gp/T/ipykernel_80434/1032975026.py:1: DtypeWarning: Columns (5,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  main = pd.read_csv('input_data/3_ML_outputs/datasets/PredictingSLResistanceFeatures_main.csv')

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,StringInteractionWithTarget,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# STRING SCORE

In [30]:
string_interaction_biomarker = pd.read_csv('input_data/3_ML_outputs/feature_output/string_score_query_biomarker.csv')
main['StringInteractionWithBiomarker'] = string_interaction_biomarker['StringInteractionWithBiomarker']
main['StringInteractionWithBiomarker'] = main['StringInteractionWithBiomarker'] / 1000
main['StringInteractionWithBiomarker'] = main['StringInteractionWithBiomarker'].fillna(0)
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,StringInteractionWithTarget,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
string_interaction_target1 = pd.read_csv('input_data/3_ML_outputs/feature_output/string_score_query_target1.csv')
string_interaction_target2 = pd.read_csv('input_data/3_ML_outputs/feature_output/string_score_query_target2.csv')

def select_highest_or_available(val1, val2):
    if pd.isna(val1) and pd.isna(val2):
        return np.nan
    elif pd.isna(val1):
        return val2
    elif pd.isna(val2):
        return val1
    else:
        return max(val1, val2,key=abs)

# Insert the resulting values into the main DataFrame
main['StringInteractionWithTarget']= [
    select_highest_or_available(a, b) for a, b in zip(string_interaction_target1['StringInteractionWithTarget'], string_interaction_target2['StringInteractionWithTarget2'])]
main['StringInteractionWithTarget']= main['StringInteractionWithTarget']/1000
main['StringInteractionWithTarget'] = main['StringInteractionWithTarget'].fillna(0)

main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,StringInteractionWithTarget,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,0.188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Coexpression

In [32]:
gtex_coexpression_biomarker = pd.read_csv('input_data/3_ML_outputs/feature_output/gtex_co_expression_biomarker_query.csv')
main['CoexpressionWithBiomarker'] = gtex_coexpression_biomarker['spearman_corr']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,StringInteractionWithTarget,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.999,0.013761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.964,0.537352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.510,0.509329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.183,0.034710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.000,0.605543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000,0.465072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.000,0.157205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,0.188,0.285345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.000,0.404083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.000,0.617853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
gtex_coexpression_target1 = pd.read_csv('input_data/3_ML_outputs/feature_output/gtex_co_expression_target1_query.csv')
gtex_coexpression_target2 = pd.read_csv('input_data/3_ML_outputs/feature_output/gtex_co_expression_target2_query.csv')

def select_highest_or_available(val1, val2):
    if pd.isna(val1) and pd.isna(val2):
        return np.nan
    elif pd.isna(val1):
        return val2
    elif pd.isna(val2):
        return val1
    else:
        return max(val1, val2,key=abs)

# Insert the resulting values into the main DataFrame
main['CoexpressionWithTarget']= [
    select_highest_or_available(a, b) for a, b in zip(gtex_coexpression_target1['spearman_corr'], gtex_coexpression_target2['spearman_corr'])]
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,StringInteractionWithTarget,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.999,0.013761,0.343676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.964,0.537352,0.172538,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.510,0.509329,0.413849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.183,0.034710,0.285614,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.000,0.605543,0.555392,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000,0.465072,0.378811,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.000,0.157205,0.505264,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,0.188,0.285345,0.246415,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.000,0.404083,0.356170,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.000,0.617853,0.339022,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
main['AvgExpression']= gtex_coexpression_biomarker['A2_mean_expr']
main['ExpressionVariance'] = gtex_coexpression_biomarker['A2_expr_variance']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.013761,0.343676,28.070952,NaN,NaN,NaN,NaN,NaN,NaN,291.159967
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.537352,0.172538,67.850543,NaN,NaN,NaN,NaN,NaN,NaN,1666.329823
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.509329,0.413849,37.713592,NaN,NaN,NaN,NaN,NaN,NaN,533.850119
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.034710,0.285614,12.880992,NaN,NaN,NaN,NaN,NaN,NaN,46.175986
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.605543,0.555392,15.041967,NaN,NaN,NaN,NaN,NaN,NaN,45.769746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.465072,0.378811,0.541083,NaN,NaN,NaN,NaN,NaN,NaN,2.097155
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.157205,0.505264,13.679719,NaN,NaN,NaN,NaN,NaN,NaN,102.933050
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,0.285345,0.246415,263.420614,NaN,NaN,NaN,NaN,NaN,NaN,73339.950606
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.404083,0.356170,18.951936,NaN,NaN,NaN,NaN,NaN,NaN,102.379095
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.617853,0.339022,9.353029,NaN,NaN,NaN,NaN,NaN,NaN,29.668770

# Coessentiality

In [35]:
coessentiality_biomarker = pd.read_csv('input_data/3_ML_outputs/feature_output/coessentiality_biomarker_query.csv')
main['CoessentialityWithBiomarker'] = coessentiality_biomarker['Correlation']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.013761,0.343676,28.070952,-0.171736,NaN,NaN,NaN,NaN,NaN,291.159967
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.537352,0.172538,67.850543,0.027675,NaN,NaN,NaN,NaN,NaN,1666.329823
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.509329,0.413849,37.713592,0.398942,NaN,NaN,NaN,NaN,NaN,533.850119
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.034710,0.285614,12.880992,0.317354,NaN,NaN,NaN,NaN,NaN,46.175986
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.605543,0.555392,15.041967,0.064477,NaN,NaN,NaN,NaN,NaN,45.769746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.465072,0.378811,0.541083,-0.011334,NaN,NaN,NaN,NaN,NaN,2.097155
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.157205,0.505264,13.679719,-0.003391,NaN,NaN,NaN,NaN,NaN,102.933050
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,0.285345,0.246415,263.420614,-0.025038,NaN,NaN,NaN,NaN,NaN,73339.950606
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.404083,0.356170,18.951936,-0.057762,NaN,NaN,NaN,NaN,NaN,102.379095
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.617853,0.339022,9.353029,-0.011750,NaN,NaN,NaN,NaN,NaN,29.668770

In [36]:
coessentiality_target1 = pd.read_csv('input_data/3_ML_outputs/feature_output/coessentiality_target1_query.csv')
coessentiality_target2 = pd.read_csv('input_data/3_ML_outputs/feature_output/coessentiality_target2_query.csv')

def select_highest_or_available(val1, val2):
    if pd.isna(val1) and pd.isna(val2):
        return np.nan
    elif pd.isna(val1):
        return val2
    elif pd.isna(val2):
        return val1
    else:
        return max(val1, val2,key=abs)

# Insert the resulting values into the main DataFrame
main['CoessentialityWithTarget']= [
    select_highest_or_available(a, b) for a, b in zip(coessentiality_target1['Correlation'], coessentiality_target2['Correlation'])]

main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,CoexpressionWithBiomarker,CoexpressionWithTarget,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.013761,0.343676,28.070952,-0.171736,0.004864,NaN,NaN,NaN,NaN,291.159967
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.537352,0.172538,67.850543,0.027675,-0.219149,NaN,NaN,NaN,NaN,1666.329823
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.509329,0.413849,37.713592,0.398942,-0.197234,NaN,NaN,NaN,NaN,533.850119
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.034710,0.285614,12.880992,0.317354,-0.119301,NaN,NaN,NaN,NaN,46.175986
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.605543,0.555392,15.041967,0.064477,-0.167807,NaN,NaN,NaN,NaN,45.769746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.465072,0.378811,0.541083,-0.011334,-0.075569,NaN,NaN,NaN,NaN,2.097155
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.157205,0.505264,13.679719,-0.003391,0.021953,NaN,NaN,NaN,NaN,102.933050
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,0.285345,0.246415,263.420614,-0.025038,-0.016839,NaN,NaN,NaN,NaN,73339.950606
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.404083,0.356170,18.951936,-0.057762,0.020199,NaN,NaN,NaN,NaN,102.379095
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.617853,0.339022,9.353029,-0.011750,-0.052807,NaN,NaN,NaN,NaN,29.668770

In [37]:
main['EssentialityVariance'] = coessentiality_biomarker['Biomarker_Essentiality_Variance']
main['EssentialityVariance'] = main['EssentialityVariance'].fillna(0)
main['EssentialityAverage'] = coessentiality_biomarker['Biomarker_Essentiality_Average']
main['EssentialityAverage'] = main['EssentialityAverage'].fillna(0)
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,28.070952,-0.171736,0.004864,NaN,NaN,NaN,NaN,291.159967,0.019359,0.131894
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,67.850543,0.027675,-0.219149,NaN,NaN,NaN,NaN,1666.329823,0.019238,-0.020458
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,37.713592,0.398942,-0.197234,NaN,NaN,NaN,NaN,533.850119,0.194427,0.089340
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,12.880992,0.317354,-0.119301,NaN,NaN,NaN,NaN,46.175986,0.155817,-0.340644
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,15.041967,0.064477,-0.167807,NaN,NaN,NaN,NaN,45.769746,0.074343,0.205940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.541083,-0.011334,-0.075569,NaN,NaN,NaN,NaN,2.097155,0.009856,0.053250
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,13.679719,-0.003391,0.021953,NaN,NaN,NaN,NaN,102.933050,0.016370,0.145534
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,263.420614,-0.025038,-0.016839,NaN,NaN,NaN,NaN,73339.950606,0.016416,0.040647
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,18.951936,-0.057762,0.020199,NaN,NaN,NaN,NaN,102.379095,0.014429,0.132027
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,9.353029,-0.011750,-0.052807,NaN,NaN,NaN,NaN,29.668770,0.027258,0.261420

# Shared PPI BIOGRID

In [38]:
shared_ppi_biomarker = pd.read_csv('input_data/3_ML_outputs/feature_output/fet_ppi_overlap_biomarker_query.csv')
main['FET_SharedInteractors_Biomarker_BIOGRID'] = shared_ppi_biomarker['fet_ppi_overlap']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,28.070952,-0.171736,0.004864,14.036345,NaN,NaN,NaN,291.159967,0.019359,0.131894
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,67.850543,0.027675,-0.219149,17.368386,NaN,NaN,NaN,1666.329823,0.019238,-0.020458
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,37.713592,0.398942,-0.197234,3.468631,NaN,NaN,NaN,533.850119,0.194427,0.089340
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,12.880992,0.317354,-0.119301,35.100297,NaN,NaN,NaN,46.175986,0.155817,-0.340644
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,15.041967,0.064477,-0.167807,11.767982,NaN,NaN,NaN,45.769746,0.074343,0.205940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.541083,-0.011334,-0.075569,0.000000,NaN,NaN,NaN,2.097155,0.009856,0.053250
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,13.679719,-0.003391,0.021953,-0.112343,NaN,NaN,NaN,102.933050,0.016370,0.145534
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,263.420614,-0.025038,-0.016839,5.952641,NaN,NaN,NaN,73339.950606,0.016416,0.040647
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,18.951936,-0.057762,0.020199,1.097225,NaN,NaN,NaN,102.379095,0.014429,0.132027
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,9.353029,-0.011750,-0.052807,0.091670,NaN,NaN,NaN,29.668770,0.027258,0.261420

In [39]:
shared_ppi_target1 = pd.read_csv('input_data/3_ML_outputs/feature_output/fet_ppi_overlap_target1_query.csv')
shared_ppi_target2 = pd.read_csv('input_data/3_ML_outputs/feature_output/fet_ppi_overlap_target2_query.csv')

def select_highest_or_available(val1, val2):
    if pd.isna(val1) and pd.isna(val2):
        return np.nan
    elif pd.isna(val1):
        return val2
    elif pd.isna(val2):
        return val1
    else:
        return max(val1, val2,key=abs)

# Insert the resulting values into the main DataFrame
main['FET_SharedInteractors_Target_BIOGRID']= [
    select_highest_or_available(a, b) for a, b in zip(shared_ppi_target1['fet_ppi_overlap'], shared_ppi_target2['fet_ppi_overlap'])]

main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,28.070952,-0.171736,0.004864,14.036345,38.971872,NaN,NaN,291.159967,0.019359,0.131894
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,67.850543,0.027675,-0.219149,17.368386,7.069189,NaN,NaN,1666.329823,0.019238,-0.020458
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,37.713592,0.398942,-0.197234,3.468631,8.158703,NaN,NaN,533.850119,0.194427,0.089340
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,12.880992,0.317354,-0.119301,35.100297,8.312495,NaN,NaN,46.175986,0.155817,-0.340644
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,15.041967,0.064477,-0.167807,11.767982,0.594197,NaN,NaN,45.769746,0.074343,0.205940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.541083,-0.011334,-0.075569,0.000000,0.000000,NaN,NaN,2.097155,0.009856,0.053250
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,13.679719,-0.003391,0.021953,-0.112343,0.511541,NaN,NaN,102.933050,0.016370,0.145534
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,263.420614,-0.025038,-0.016839,5.952641,12.893010,NaN,NaN,73339.950606,0.016416,0.040647
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,18.951936,-0.057762,0.020199,1.097225,3.010342,NaN,NaN,102.379095,0.014429,0.132027
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,9.353029,-0.011750,-0.052807,0.091670,1.583333,NaN,NaN,29.668770,0.027258,0.261420

# Shared PPI STRING

In [40]:
shared_ppi_biomarker = pd.read_csv('input_data/3_ML_outputs/feature_output/fet_ppi_overlap_biomarker_query_string.csv')
main['FET_SharedInteractors_Biomarker_STRING'] = shared_ppi_biomarker['fet_ppi_overlap']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,28.070952,-0.171736,0.004864,14.036345,38.971872,114.152228,NaN,291.159967,0.019359,0.131894
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,67.850543,0.027675,-0.219149,17.368386,7.069189,34.068956,NaN,1666.329823,0.019238,-0.020458
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,37.713592,0.398942,-0.197234,3.468631,8.158703,144.356054,NaN,533.850119,0.194427,0.089340
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,12.880992,0.317354,-0.119301,35.100297,8.312495,68.669701,NaN,46.175986,0.155817,-0.340644
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,15.041967,0.064477,-0.167807,11.767982,0.594197,-0.097172,NaN,45.769746,0.074343,0.205940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.541083,-0.011334,-0.075569,0.000000,0.000000,0.000000,NaN,2.097155,0.009856,0.053250
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,13.679719,-0.003391,0.021953,-0.112343,0.511541,-0.202768,NaN,102.933050,0.016370,0.145534
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,263.420614,-0.025038,-0.016839,5.952641,12.893010,9.351460,NaN,73339.950606,0.016416,0.040647
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,18.951936,-0.057762,0.020199,1.097225,3.010342,-0.203459,NaN,102.379095,0.014429,0.132027
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,9.353029,-0.011750,-0.052807,0.091670,1.583333,0.385866,NaN,29.668770,0.027258,0.261420

In [41]:
shared_ppi_target1 = pd.read_csv('input_data/3_ML_outputs/feature_output/fet_ppi_overlap_target1_query_string.csv')
shared_ppi_target2 = pd.read_csv('input_data/3_ML_outputs/feature_output/fet_ppi_overlap_target2_query_string.csv')

def select_highest_or_available(val1, val2):
    if pd.isna(val1) and pd.isna(val2):
        return np.nan
    elif pd.isna(val1):
        return val2
    elif pd.isna(val2):
        return val1
    else:
        return max(val1, val2,key=abs)

# Insert the resulting values into the main DataFrame
main['FET_SharedInteractors_Target_STRING']= [
    select_highest_or_available(a, b) for a, b in zip(shared_ppi_target1['fet_ppi_overlap'], shared_ppi_target2['fet_ppi_overlap'])]

main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,AvgExpression,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,28.070952,-0.171736,0.004864,14.036345,38.971872,114.152228,323.306215,291.159967,0.019359,0.131894
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,67.850543,0.027675,-0.219149,17.368386,7.069189,34.068956,83.017283,1666.329823,0.019238,-0.020458
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,37.713592,0.398942,-0.197234,3.468631,8.158703,144.356054,62.190596,533.850119,0.194427,0.089340
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,12.880992,0.317354,-0.119301,35.100297,8.312495,68.669701,34.650616,46.175986,0.155817,-0.340644
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,15.041967,0.064477,-0.167807,11.767982,0.594197,-0.097172,-0.188936,45.769746,0.074343,0.205940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.541083,-0.011334,-0.075569,0.000000,0.000000,0.000000,0.000000,2.097155,0.009856,0.053250
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,13.679719,-0.003391,0.021953,-0.112343,0.511541,-0.202768,0.000000,102.933050,0.016370,0.145534
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,263.420614,-0.025038,-0.016839,5.952641,12.893010,9.351460,16.005291,73339.950606,0.016416,0.040647
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,18.951936,-0.057762,0.020199,1.097225,3.010342,-0.203459,0.000000,102.379095,0.014429,0.132027
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,9.353029,-0.011750,-0.052807,0.091670,1.583333,0.385866,4.655171,29.668770,0.027258,0.261420

# BIOGRID Physical Binary Interactions

In [42]:
biogrid_biomarker_interaction = pd.read_csv('input_data/3_ML_outputs/feature_output/biogrid_biomarker_query.csv')
main["BIOGRIDPhysicalInteractionQueryBiomarker"] = biogrid_biomarker_interaction['BIOGRIDPhysicalInteractionQueryBiomarker']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,CoessentialityWithBiomarker,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,-0.171736,0.004864,14.036345,38.971872,114.152228,323.306215,291.159967,0.019359,0.131894,1
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,0.027675,-0.219149,17.368386,7.069189,34.068956,83.017283,1666.329823,0.019238,-0.020458,0
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,0.398942,-0.197234,3.468631,8.158703,144.356054,62.190596,533.850119,0.194427,0.089340,0
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,0.317354,-0.119301,35.100297,8.312495,68.669701,34.650616,46.175986,0.155817,-0.340644,0
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.064477,-0.167807,11.767982,0.594197,-0.097172,-0.188936,45.769746,0.074343,0.205940,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,-0.011334,-0.075569,0.000000,0.000000,0.000000,0.000000,2.097155,0.009856,0.053250,0
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,-0.003391,0.021953,-0.112343,0.511541,-0.202768,0.000000,102.933050,0.016370,0.145534,0
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,-0.025038,-0.016839,5.952641,12.893010,9.351460,16.005291,73339.950606,0.016416,0.040647,0
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,-0.057762,0.020199,1.097225,3.010342,-0.203459,0.000000,102.379095,0.014429,0.132027,0
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,-0.011750,-0.052807,0.091670,1.583333,0.385866,4.655171,29.668770,0.027258,0.261420,0

In [43]:
biogrid_target_interaction = pd.read_csv('input_data/3_ML_outputs/feature_output/biogrid_target_query.csv')
main["BIOGRIDPhysicalInteractionQueryTarget"] = biogrid_target_interaction['BIOGRIDPhysicalInteractionQueryTarget']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,CoessentialityWithTarget,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker,BIOGRIDPhysicalInteractionQueryTarget
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,0.004864,14.036345,38.971872,114.152228,323.306215,291.159967,0.019359,0.131894,1,1
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,-0.219149,17.368386,7.069189,34.068956,83.017283,1666.329823,0.019238,-0.020458,0,0
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,-0.197234,3.468631,8.158703,144.356054,62.190596,533.850119,0.194427,0.089340,0,0
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,-0.119301,35.100297,8.312495,68.669701,34.650616,46.175986,0.155817,-0.340644,0,0
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,-0.167807,11.767982,0.594197,-0.097172,-0.188936,45.769746,0.074343,0.205940,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,-0.075569,0.000000,0.000000,0.000000,0.000000,2.097155,0.009856,0.053250,0,0
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.021953,-0.112343,0.511541,-0.202768,0.000000,102.933050,0.016370,0.145534,0,0
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,-0.016839,5.952641,12.893010,9.351460,16.005291,73339.950606,0.016416,0.040647,0,0
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,0.020199,1.097225,3.010342,-0.203459,0.000000,102.379095,0.014429,0.132027,0,0
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,-0.052807,0.091670,1.583333,0.385866,4.655171,29.668770,0.027258,0.261420,0,0

# TSG or oncogen

In [44]:
biomarker_type = pd.read_csv('input_data/3_ML_outputs/feature_output/biomarker_type.csv')
main['BiomarkerType'] = biomarker_type['TSG_Label']
main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,FET_SharedInteractors_Biomarker_BIOGRID,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker,BIOGRIDPhysicalInteractionQueryTarget,BiomarkerType
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,14.036345,38.971872,114.152228,323.306215,291.159967,0.019359,0.131894,1,1,1
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,17.368386,7.069189,34.068956,83.017283,1666.329823,0.019238,-0.020458,0,0,1
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,3.468631,8.158703,144.356054,62.190596,533.850119,0.194427,0.089340,0,0,1
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,35.100297,8.312495,68.669701,34.650616,46.175986,0.155817,-0.340644,0,0,1
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,11.767982,0.594197,-0.097172,-0.188936,45.769746,0.074343,0.205940,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000000,0.000000,0.000000,0.000000,2.097155,0.009856,0.053250,0,0,0
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,-0.112343,0.511541,-0.202768,0.000000,102.933050,0.016370,0.145534,0,0,0
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,5.952641,12.893010,9.351460,16.005291,73339.950606,0.016416,0.040647,0,0,0
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,1.097225,3.010342,-0.203459,0.000000,102.379095,0.014429,0.132027,0,0,0
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.091670,1.583333,0.385866,4.655171,29.668770,0.027258,0.261420,0,0,0

# Essentiality Percentage

In [45]:
essentiality_percentage = pd.read_csv('input_data/3_ML_outputs/feature_output/essentiality_percentage_per_gene.csv')
essentiality_percentage

       entrez_id  Essentiality_Percentage
0            1.0                 0.084890
1        29974.0                 0.254669
2            2.0                 0.000000
3       144568.0                 0.000000
4       127550.0                 0.169779
...          ...                      ...
17911   440590.0                 0.000000
17912    79699.0                 0.424448
17913     7791.0                 0.000000
17914    23140.0                 0.084890
17915    26009.0                 2.971138

[17916 rows x 2 columns]

In [46]:
# Merge using different column names
main= main.merge(
    essentiality_percentage,
    left_on="entrez_id_query",  # column in main_df
    right_on="entrez_id",       # column in ess_df
    how="left"
)

# Drop the duplicate "entrez_id" if you don’t need it
main = main.drop(columns=["entrez_id"])
main["Essentiality_Percentage"] = main["Essentiality_Percentage"].fillna(0)

main

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker,BIOGRIDPhysicalInteractionQueryTarget,BiomarkerType,Essentiality_Percentage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,38.971872,114.152228,323.306215,291.159967,0.019359,0.131894,1,1,1,0.509338
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,7.069189,34.068956,83.017283,1666.329823,0.019238,-0.020458,0,0,1,0.000000
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,8.158703,144.356054,62.190596,533.850119,0.194427,0.089340,0,0,1,11.629881
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,8.312495,68.669701,34.650616,46.175986,0.155817,-0.340644,0,0,1,1.103565
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.594197,-0.097172,-0.188936,45.769746,0.074343,0.205940,0,0,1,8.064516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144075,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000000,0.000000,0.000000,2.097155,0.009856,0.053250,0,0,0,0.000000
144076,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.511541,-0.202768,0.000000,102.933050,0.016370,0.145534,0,0,0,0.424448
144077,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,12.893010,9.351460,16.005291,73339.950606,0.016416,0.040647,0,0,0,0.000000
144078,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,3.010342,-0.203459,0.000000,102.379095,0.014429,0.132027,0,0,0,0.084890
144079,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,1.583333,0.385866,4.655171,29.668770,0.027258,0.261420,0,0,0,2.971138

In [47]:
main.to_csv('input_data/3_ML_outputs/datasets/PredictingSLResistanceFeatures_main_withfeatures.csv',index=False)

In [48]:
main_dropna = main.dropna(subset=['CoexpressionWithBiomarker','CoexpressionWithTarget']).reset_index(drop=True)
main_dropna

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,FET_SharedInteractors_Target_BIOGRID,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker,BIOGRIDPhysicalInteractionQueryTarget,BiomarkerType,Essentiality_Percentage
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,38.971872,114.152228,323.306215,291.159967,0.019359,0.131894,1,1,1,0.509338
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,7.069189,34.068956,83.017283,1666.329823,0.019238,-0.020458,0,0,1,0.000000
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,8.158703,144.356054,62.190596,533.850119,0.194427,0.089340,0,0,1,11.629881
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,8.312495,68.669701,34.650616,46.175986,0.155817,-0.340644,0,0,1,1.103565
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,0.594197,-0.097172,-0.188936,45.769746,0.074343,0.205940,0,0,1,8.064516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142979,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000000,0.000000,0.000000,2.097155,0.009856,0.053250,0,0,0,0.000000
142980,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,0.511541,-0.202768,0.000000,102.933050,0.016370,0.145534,0,0,0,0.424448
142981,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,12.893010,9.351460,16.005291,73339.950606,0.016416,0.040647,0,0,0,0.000000
142982,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,3.010342,-0.203459,0.000000,102.379095,0.014429,0.132027,0,0,0,0.084890
142983,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,1.583333,0.385866,4.655171,29.668770,0.027258,0.261420,0,0,0,2.971138

In [49]:
main_dropna['Class_Processed'] = main_dropna["Class"].map({
    'Resistance': 1,
    'Non_Resistance': 0
})
main_dropna

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker,BIOGRIDPhysicalInteractionQueryTarget,BiomarkerType,Essentiality_Percentage,Class_Processed
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,114.152228,323.306215,291.159967,0.019359,0.131894,1,1,1,0.509338,1
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,34.068956,83.017283,1666.329823,0.019238,-0.020458,0,0,1,0.000000,1
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,144.356054,62.190596,533.850119,0.194427,0.089340,0,0,1,11.629881,1
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,68.669701,34.650616,46.175986,0.155817,-0.340644,0,0,1,1.103565,1
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,-0.097172,-0.188936,45.769746,0.074343,0.205940,0,0,1,8.064516,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142979,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000000,0.000000,2.097155,0.009856,0.053250,0,0,0,0.000000,0
142980,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,-0.202768,0.000000,102.933050,0.016370,0.145534,0,0,0,0.424448,0
142981,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,9.351460,16.005291,73339.950606,0.016416,0.040647,0,0,0,0.000000,0
142982,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,-0.203459,0.000000,102.379095,0.014429,0.132027,0,0,0,0.084890,0
142983,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.385866,4.655171,29.668770,0.027258,0.261420,0,0,0,2.971138,0

In [50]:
main_dropna.to_csv('input_data/3_ML_outputs/datasets/PredictingSLResistanceFeatures_main_withfeatures_dropna_filtered.csv',index=False)

In [51]:
subset=['SL_Pair', 'Query', 'Biomarker', 'Target1', 'Target2',
       'entrez_id_query', 'hgnc_id_query', 'ensembl_gene_id_query',
       'entrez_id_biomarker', 'hgnc_id_biomarker', 'ensembl_gene_id_biomarker',
       'entrez_id_target1', 'hgnc_id_target1', 'ensembl_gene_id_target1',
       'entrez_id_target2', 'hgnc_id_target2', 'ensembl_gene_id_target2',
       'StringInteractionWithBiomarker',
       'StringInteractionWithTarget', 'CoexpressionWithBiomarker',
       'CoexpressionWithTarget', 'AvgExpression',
       'CoessentialityWithBiomarker', 'CoessentialityWithTarget',
       'FET_SharedInteractors_Biomarker_BIOGRID', 'FET_SharedInteractors_Target_BIOGRID',
       'FET_SharedInteractors_Biomarker_STRING', 'FET_SharedInteractors_Target_STRING',
       'BIOGRIDPhysicalInteractionQueryBiomarker',
       'BIOGRIDPhysicalInteractionQueryTarget','ExpressionVariance','EssentialityVariance',
       'EssentialityAverage','Class_Processed']
# Drop duplicates
main_unique = main_dropna.drop_duplicates(subset=subset)
main_unique

,Screen,SL_Pair,Query,Biomarker,Target1,Target2,entrez_id_query,hgnc_id_query,ensembl_gene_id_query,entrez_id_biomarker,...,FET_SharedInteractors_Biomarker_STRING,FET_SharedInteractors_Target_STRING,ExpressionVariance,EssentialityVariance,EssentialityAverage,BIOGRIDPhysicalInteractionQueryBiomarker,BIOGRIDPhysicalInteractionQueryTarget,BiomarkerType,Essentiality_Percentage,Class_Processed
0,Dunn,PTEN_PIK3CB,PIK3R2,PTEN,PIK3CB,NaN,5296.0,HGNC:8980,ENSG00000105647,5728.0,...,114.152228,323.306215,291.159967,0.019359,0.131894,1,1,1,0.509338,1
1,Dunn,PTEN_PIK3CB,INPPL1,PTEN,PIK3CB,NaN,3636.0,HGNC:6080,ENSG00000165458,5728.0,...,34.068956,83.017283,1666.329823,0.019238,-0.020458,0,0,1,0.000000,1
2,Dunn,PTEN_PIK3CB,TSC2,PTEN,PIK3CB,NaN,7249.0,HGNC:12363,ENSG00000103197,5728.0,...,144.356054,62.190596,533.850119,0.194427,0.089340,0,0,1,11.629881,1
3,Dunn,PTEN_PIK3CB,NF2,PTEN,PIK3CB,NaN,4771.0,HGNC:7773,ENSG00000186575,5728.0,...,68.669701,34.650616,46.175986,0.155817,-0.340644,0,0,1,1.103565,1
4,Dunn,PTEN_PIK3CB,CXorf56,PTEN,PIK3CB,NaN,63932.0,HGNC:26239,ENSG00000018610,5728.0,...,-0.097172,-0.188936,45.769746,0.074343,0.205940,0,0,1,8.064516,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142979,Hayes_Krall,NRAS_MEK,ZYG11A,NRAS,MEK1,MEK2,440590.0,HGNC:32058,ENSG00000203995,4893.0,...,0.000000,0.000000,2.097155,0.009856,0.053250,0,0,0,0.000000,0
142980,Hayes_Krall,NRAS_MEK,ZYG11B,NRAS,MEK1,MEK2,79699.0,HGNC:25820,ENSG00000162378,4893.0,...,-0.202768,0.000000,102.933050,0.016370,0.145534,0,0,0,0.424448,0
142981,Hayes_Krall,NRAS_MEK,ZYX,NRAS,MEK1,MEK2,7791.0,HGNC:13200,ENSG00000159840,4893.0,...,9.351460,16.005291,73339.950606,0.016416,0.040647,0,0,0,0.000000,0
142982,Hayes_Krall,NRAS_MEK,ZZEF1,NRAS,MEK1,MEK2,23140.0,HGNC:29027,ENSG00000074755,4893.0,...,-0.203459,0.000000,102.379095,0.014429,0.132027,0,0,0,0.084890,0
142983,Hayes_Krall,NRAS_MEK,ZZZ3,NRAS,MEK1,MEK2,26009.0,HGNC:24523,ENSG00000036549,4893.0,...,0.385866,4.655171,29.668770,0.027258,0.261420,0,0,0,2.971138,0

In [52]:
main_unique.to_csv('input_data/3_ML_outputs/datasets/PredictingSLResistanceFeatures_main_withfeatures_dropna_remove_duplicate.csv',index=False)